<a href="https://colab.research.google.com/github/sudiksha2004/Amazon-Clone/blob/main/TensorFlow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x #this line is not required unles yhou are in a notebook

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>




> Creating Tensors

Below is an example of how to ceate tensors

In [ ]:
string = tf.Variable("This is a variable",tf.string)
number = tf.Variable(324,tf.int16)
float = tf.Variable(3.567,tf.float64)



>Rank/Degree of Tensors

Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0,as they have a single value and no dimensions

In [ ]:
rank1_tensor= tf.Variable(["Test","Ok","Tim"],tf.string)
rank2_tensor = tf.Variable([["Test","Ok","s"],["test","yes","k"]],tf.string)


To determine the rank of a tensor we can do the following method

In [ ]:
tf.rank(rank2_tensor)


<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.rank(rank1_tensor)


<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.rank(number)


<tf.Tensor: shape=(), dtype=int32, numpy=0>

Shape of a tensor

Shape of a tensor is simply the amount of elements that exists in each dimension.Tensorflow will try to determine the shape of tensor but sometimes it may be unknown

We can use the** shape** attribute to determine the shape of a tensor

In [ ]:
rank2_tensor.shape

TensorShape([2, 3])